defaults:
  - _self_
  - override hydra/launcher: basic

hydra:
  run:
    dir: plan_outputs/${now:%Y%m%d%H%M%S}_${replace_slash:${model_name}}_gH${goal_H}

ckpt_base_path: /kaggle/input/PushT_Checkpoint
model_name: pusht_ours
model_epoch: latest

seed: 99
n_evals: 1
goal_source: 'dset'
goal_H: 5
n_plot_samples: 1

debug_dset_init: False

objective:
  _target_: planning.objectives.create_objective_fn
  alpha: 1
  base: 2
  mode: last

planner:
  _target_: planning.mpc.MPCPlanner
  max_iter: 60
  n_taken_actions: 5
  sub_planner:
    target: planning.cem.CEMPlanner
    horizon: 5
    topk: 10
    num_samples: 50
    sample_batch_size: 50
    var_scale: 1
    opt_steps: 5
    eval_every: 1
  name: mpc_cem
